# generated by datamodel-codegen:
#   filename:  oas3_catalog.json
#   timestamp: 2026-06-23T14:13:37+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from uuid import UUID
from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class Uuid(RootModel[UUID]):
    root: UUID


class AudienceEnum(
    RootModel[
        Literal[
            "DataEngineer",
            "BIEngineer",
            "DataAnalyst",
            "DataScientist",
            "BusinessAnalyst",
            "SoftwareEngineer",
            "BusinessUser",
            "Executive",
        ]
    ]
):
    root: Annotated[
        Literal[
            "DataEngineer",
            "BIEngineer",
            "DataAnalyst",
            "DataScientist",
            "BusinessAnalyst",
            "SoftwareEngineer",
            "BusinessUser",
            "Executive",
        ],
        Field(description="Audience enumeration for data products."),
    ]


class CatalogApiServiceOrderDirection(RootModel[Literal["asc", "desc"]]):
    root: Annotated[
        Literal["asc", "desc"],
        Field(description="Ordering configuration for API service results."),
    ]


class CatalogModelContactsValueInner(BaseModel):
    id: Annotated[Uuid | None, Field(description="AAD oid for the person or group")] = None
    description: Annotated[
        str | None, Field(description="A description of this user assignment")
    ] = None


class CatalogModelCriticalDataElementDataTypeEnum(
    RootModel[Literal["TEXT", "NUMBER", "DATETIME", "BOOLEAN"]]
):
    root: Annotated[
        Literal["TEXT", "NUMBER", "DATETIME", "BOOLEAN"],
        Field(description="Data types supported for critical data elements."),
    ]


class CatalogModelDataAssetSchema(BaseModel):
    name: Annotated[str | None, Field(description="Name of the asset.")] = None
    description: Annotated[str | None, Field(description="Description of the asset.")] = None
    classifications: Annotated[
        list[str] | None,
        Field(description="A list of classification labels. example: [PII, PHI]"),
    ] = None
    type: Annotated[str | None, Field(description="Type of the asset.")] = None


class CatalogModelDataAssetSource(BaseModel):
    type: Annotated[str | None, Field(description="The type of the data asset source.")] = None
    assetId: Annotated[Uuid | None, Field(description="Link to the data map asset ID.")] = None
    assetType: Annotated[
        str | None,
        Field(description="Data map asset type. Example: adls_gen2_path, azure_sql_table, etc."),
    ] = None
    assetAttributes: Annotated[
        list[str] | None, Field(description="Type properties of the asset.")
    ] = None
    fqn: Annotated[str | None, Field(description="Fully qualified name of the data asset.")] = None
    accountName: Annotated[
        str | None, Field(description="The data map account name of the data asset.")
    ] = None
    lastRefreshedAt: Annotated[
        AwareDatetime | None, Field(description="Date of the last sync time.")
    ] = None
    lastRefreshedBy: Annotated[
        str | None, Field(description="ID of the user who last refreshed the asset.")
    ] = None


class CatalogModelDataAssetSourceRequest(BaseModel):
    assetId: Annotated[Uuid | None, Field(description="Link to the data map asset ID.")] = None


class CatalogModelDataProductAllOfAdditionalProperties(BaseModel):
    assetCount: Annotated[
        int | None, Field(description="The number of assets in the data product.")
    ] = None


class CatalogModelDataProductTypeEnum(
    RootModel[
        Literal[
            "Master",
            "Reference",
            "Analytical",
            "AI",
            "MasterDataAndReferenceData",
            "BusinessSystemOrApplication",
            "ModelTypes",
            "DashboardsOrReports",
            "Operational",
            "MLAITrainingDataSet",
            "MLAITestingDataSet",
            "TransactionalDataset",
            "AnalyticsModel",
            "SemanticModel",
        ]
    ]
):
    root: Annotated[
        Literal[
            "Master",
            "Reference",
            "Analytical",
            "AI",
            "MasterDataAndReferenceData",
            "BusinessSystemOrApplication",
            "ModelTypes",
            "DashboardsOrReports",
            "Operational",
            "MLAITrainingDataSet",
            "MLAITestingDataSet",
            "TransactionalDataset",
            "AnalyticsModel",
            "SemanticModel",
        ],
        Field(description="CatalogModelDataProductTypeEnum"),
    ]


class CatalogModelDomainAllOfThumbnail(BaseModel):
    color: Annotated[str | None, Field(description="The color of the thumbnail.")] = None


class CatalogModelDomainTypeEnum(
    RootModel[Literal["FunctionalUnit", "LineOfBusiness", "DataDomain", "Regulatory", "Project"]]
):
    root: Annotated[
        Literal["FunctionalUnit", "LineOfBusiness", "DataDomain", "Regulatory", "Project"],
        Field(description="CatalogModelDomainTypeEnum"),
    ]


class CatalogModelExternalLink(BaseModel):
    url: Annotated[AnyUrl | None, Field(description="The URL of the external link.")] = None
    name: Annotated[str | None, Field(description="The name of the external link.")] = None
    dataAssetId: Annotated[
        Uuid | None,
        Field(description="The data asset identifier associated with the link."),
    ] = None


class CatalogModelManagedAttribute(BaseModel):
    name: Annotated[str | None, Field(description="The name of the managed attribute.")] = None
    value: Annotated[str | None, Field(description="The value of the attribute.")] = None
    isRequired: Annotated[
        bool | None, Field(description="Whether this attribute is required.")
    ] = None


class CatalogModelStatus(RootModel[Literal["DRAFT", "PUBLISHED", "EXPIRED"]]):
    root: Annotated[
        Literal["DRAFT", "PUBLISHED", "EXPIRED"],
        Field(description="Status of a catalog model entity indicating its lifecycle state."),
    ]


class CatalogModelTermResource(BaseModel):
    name: Annotated[str | None, Field(description="The name of the resource.")] = None
    url: Annotated[AnyUrl | None, Field(description="The URL of the resource.")] = None


class CdeRelationship(BaseModel):
    relationshipType: Annotated[str | None, Field(description="Type of the relationship.")] = None
    entityId: Annotated[Uuid, Field(description="Unique identifier of the related entity.")]


class Condition(BaseModel):
    attributeName: Annotated[str, Field(description="The name of the attribute.")]
    attributeValueIncludes: Annotated[
        str | None, Field(description="The operator of the condition.")
    ] = None
    attributeValueIncludedIn: Annotated[
        list[str] | None, Field(description="The values included in the condition.")
    ] = None
    fromRule: Annotated[
        str | None, Field(description="The rule from which the condition is derived.")
    ] = None


class ContactsMap(BaseModel):
    owner: Annotated[
        list[CatalogModelContactsValueInner] | None,
        Field(description="List of owner contacts."),
    ] = None
    expert: Annotated[
        list[CatalogModelContactsValueInner] | None,
        Field(description="List of expert contacts."),
    ] = None
    databaseAdmin: Annotated[
        list[CatalogModelContactsValueInner] | None,
        Field(description="List of database administrator contacts."),
    ] = None


class DataAssetAdlsGen2PathTypeProperties(BaseModel):
    serverEndpoint: Annotated[
        AnyUrl | None, Field(description="The server endpoint of the ADLS Gen2 path.")
    ] = None
    container: Annotated[
        str | None, Field(description="The container name of the ADLS Gen2 path.")
    ] = None
    folderPath: Annotated[
        str | None, Field(description="The folder path of the ADLS Gen2 path.")
    ] = None
    fileName: Annotated[str | None, Field(description="The file name of the ADLS Gen2 path.")] = (
        None
    )


class DataAssetProvisioningState(RootModel[Literal["Unknown", "Succeeded", "SoftDeleted"]]):
    root: Annotated[
        Literal["Unknown", "Succeeded", "SoftDeleted"],
        Field(description="The provisioning state of a data asset."),
    ]


class DataAssetQueryRequest(BaseModel):
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    sourceAssetIds: Annotated[
        list[str] | None, Field(description="To filter by data map asset Ids.")
    ] = None
    assetTypes: Annotated[
        list[str] | None, Field(description="To filter by data map asset types.")
    ] = None
    includingOrphans: Annotated[bool | None, Field(description="To filter by status.")] = None


class DataAssetRelationshipType(RootModel[Literal["Related", "Synonym"]]):
    root: Annotated[
        Literal["Related", "Synonym"],
        Field(description="The type of relationship between data assets."),
    ]


class DataAssetRequest(BaseModel):
    source: Annotated[
        CatalogModelDataAssetSourceRequest | None,
        Field(description="Source of the asset."),
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None


class DataAssetSystemData(BaseModel):
    provisioningState: Annotated[
        DataAssetProvisioningState | None,
        Field(description="The provisioning state of the record."),
    ] = None
    createdAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record was created."),
    ] = None
    createdBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who created the record."),
    ] = None
    lastModifiedAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record was last modified."),
    ] = None
    lastModifiedBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who last modified the record."),
    ] = None
    expiredAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record expires."),
    ] = None
    expiredBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who expired the record."),
    ] = None


class DataAssetType(RootModel[Literal["AzureSqlTable", "ADLSGen2Path", "General"]]):
    root: Annotated[
        Literal["AzureSqlTable", "ADLSGen2Path", "General"],
        Field(description="The type of a data asset."),
    ]


class DataColumnAssetDetails(BaseModel):
    assetId: Annotated[
        str | None,
        Field(
            description="The Data Governance asset identifier, which may be absent if enrichment is not possible."
        ),
    ] = None
    name: Annotated[str | None, Field(description="The display name of the asset")] = None
    fqn: Annotated[str | None, Field(description="The fully qualified name of the asset.")] = None


class DataColumnDetails(BaseModel):
    name: Annotated[
        str | None, Field(description="The display name of the column from Data Map.")
    ] = None
    description: Annotated[
        str | None, Field(description="The description of the column from Data Map.")
    ] = None
    dataType: Annotated[
        str | None, Field(description="The data type of the column from Data Map.")
    ] = None
    qualifiedName: Annotated[
        str | None,
        Field(description="The fully qualified name of the column from Data Map."),
    ] = None


class DataColumnFieldFilter(BaseModel):
    eq: Annotated[Uuid | None, Field(description="Equals (exact match)")] = None
    ne: Annotated[Uuid | None, Field(description="Not equals")] = None
    in_: Annotated[
        list[Uuid] | None,
        Field(alias="in", description="In list (matches any value)"),
    ] = None
    nin: Annotated[list[Uuid] | None, Field(description="Not in list (excludes all values)")] = (
        None
    )


class DataColumnQueryFilter(BaseModel):
    and_: Annotated[
        list[DataColumnQueryFilter] | None,
        Field(alias="and", description="Logical AND: All conditions must match."),
    ] = None
    or_: Annotated[
        list[DataColumnQueryFilter] | None,
        Field(alias="or", description="Logical OR: Any condition can match."),
    ] = None
    id: Annotated[DataColumnFieldFilter | None, Field(description="Filter by data column ID")] = (
        None
    )
    sourceAssetId: Annotated[
        DataColumnFieldFilter | None, Field(description="Filter by data column ID")
    ] = None
    sourceColumnId: Annotated[
        DataColumnFieldFilter | None, Field(description="Filter by data column ID")
    ] = None


class DataColumnQueryRequest(BaseModel):
    filter: Annotated[
        DataColumnQueryFilter | None,
        Field(description="Filter conditions with logical AND/OR combinations."),
    ] = None
    skip: Annotated[
        int | None, Field(description="Number of items to skip (pagination offset).")
    ] = None
    top: Annotated[
        int | None, Field(description="Maximum number of items to return (page size)")
    ] = None
    includingOrphans: Annotated[
        bool, Field(description="Include data columns without relationships (orphans)")
    ]
    includeColumnDetails: Annotated[
        bool | None, Field(description="Include enriched column metadata from Data Map")
    ] = None
    includeAssetDetails: Annotated[
        bool | None,
        Field(description="Include parent asset details (DG asset id, name, FQN)"),
    ] = None


class DataColumnRelationshipType(RootModel[Literal["Related", "Synonym", "Parent"]]):
    root: Annotated[
        Literal["Related", "Synonym", "Parent"],
        Field(description="The type of relationship between data columns."),
    ]


class DataColumnRelationshipWrapper(BaseModel):
    relationshipType: Annotated[
        DataColumnRelationshipType | None,
        Field(description="The type of relationship for the data column."),
    ] = None
    entityId: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the related entity."),
    ] = None


class DataColumnSource(BaseModel):
    type: Annotated[str, Field(description="The type of the entity.")]
    assetId: Annotated[Uuid, Field(description="The unique identifier of the asset.")]
    columnId: Annotated[Uuid, Field(description="The unique identifier of the Column.")]


class DataElementProperties(BaseModel):
    description: Annotated[str | None, Field(description="The first additional property.")] = None
    entityId: Annotated[str | None, Field(description="The second additional property.")] = None
    relationshipType: Annotated[
        str | None, Field(description="The third additional property.")
    ] = None


class DecisionRule(BaseModel):
    kind: Annotated[str, Field(description="The kind of decision rule.")]
    effect: Annotated[str, Field(description="The unique identifier of the decision rule.")]
    dnfCondition: Annotated[
        list[list[Condition]], Field(description="The name of the decision rule.")
    ]


class DuplicateOkrQueryRequest(BaseModel):
    definition: Annotated[
        str,
        Field(description="The keyword to search for duplicate objectives/OKRs by name."),
    ]


class DuplicateQueryRequest(BaseModel):
    nameKeyword: Annotated[
        str, Field(description="The keyword to search for duplicate elements by name.")
    ]


class EntityCount(BaseModel):
    count: Annotated[int, Field(description="Count of entities which exist.")]


class EntityReference(BaseModel):
    type: Annotated[str, Field(description="The type of the entity.")]
    referenceName: Annotated[str, Field(description="The reference name of the entity.")]


class FacetRequestObject(BaseModel):
    name: Annotated[str | None, Field(description="The name of the facet.")] = None


class FacetValue(BaseModel):
    value: Annotated[str, Field(description="The value of the facet.")]
    count: Annotated[str, Field(description="The count of items in the facet.")]


class FacetsResponse(BaseModel):
    facets: Annotated[dict[str, list[FacetValue]], Field(description="The list of facets.")]


class IngestDataColumnRequest(BaseModel):
    dataMapAssetId: Annotated[Uuid | None, Field(description="AssetId from Datamap")] = None
    dataMapColumnId: Annotated[Uuid | None, Field(description="ColumnId from Datamap")] = None


class LineageObject(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ModelsFacetRequestObject(BaseModel):
    name: Annotated[str | None, Field(description="name")] = None


class OkrSharedEntityStatus(RootModel[Literal["Draft", "Published", "Closed"]]):
    root: Annotated[
        Literal["Draft", "Published", "Closed"],
        Field(description="OkrSharedEntityStatus"),
    ]


class OkrSystemDataWithExpired(BaseModel):
    createdAt: Annotated[
        AwareDatetime | None, Field(description="The created time of the record.")
    ] = None
    createdBy: Annotated[Uuid | None, Field(description="The user who created the record.")] = None
    lastModifiedAt: Annotated[
        AwareDatetime | None,
        Field(description="The user who Last modified the record."),
    ] = None
    lastModifiedBy: Annotated[
        Uuid | None, Field(description="The user who last modified the record.")
    ] = None
    closedAt: Annotated[
        AwareDatetime | None, Field(description="The time when the record was closed.")
    ] = None
    closedBy: Annotated[Uuid | None, Field(description="The user who closed the record.")] = None


class OverallStatusEnum(RootModel[Literal["NotTracked", "OnTrack", "Behind", "AtRisk"]]):
    root: Annotated[
        Literal["NotTracked", "OnTrack", "Behind", "AtRisk"],
        Field(description="OverallStatusEnum"),
    ]


class PagedCdeRelationship(BaseModel):
    value: Annotated[
        list[CdeRelationship],
        Field(description="The CdeRelationship items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class RelatedCollectionParentCollectionTypeEnum(RootModel[Literal["CollectionReference"]]):
    root: Annotated[
        Literal["CollectionReference"],
        Field(description="Related collection parent collection type enumeration."),
    ]


class SharedEntityStatus(RootModel[Literal["Draft", "Published", "Expired"]]):
    root: Annotated[
        Literal["Draft", "Published", "Expired"],
        Field(description="Status of shared entities in the catalog."),
    ]


class SharedSearchManageAttributeSearchFilter(BaseModel):
    field: Annotated[
        str | None,
        Field(
            description="The field name to filter on. Example: 'All Attributes Types.AttributeName'"
        ),
    ] = None
    operator: Annotated[
        str | None,
        Field(
            description="The comparison operator to use for filtering. Example: 'ne' , 'eq' ,'gt' , 'ge' , 'lt' , 'le', 'contains' ,'notcontains', 'prefix','eq-any'"
        ),
    ] = None
    value: Annotated[
        str | None,
        Field(
            description="The value to compare against. Example: '2', 'LAST_24H', LAST_7D','LAST_30D',LAST_365D','MORE_THAN_365D'"
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="The data type of the filter value. Example: 'int','date','double','float',richtext','short','string','boolean','multiChoice'"
        ),
    ] = None


class SystemData(BaseModel):
    lastModifiedAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the entity was last modified."),
    ] = None
    lastModifiedBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who last modified the entity."),
    ] = None
    createdAt: Annotated[
        str | None, Field(description="The timestamp when the entity was created.")
    ] = None
    createdBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who created the entity."),
    ] = None


class TermFacetRequest(BaseModel):
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    domainIds: Annotated[list[str] | None, Field(description="To filter by domain Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    acronyms: Annotated[list[str] | None, Field(description="To filter by acronyms.")] = None
    status: Annotated[SharedEntityStatus | None, Field(description="To filter by status.")] = None
    multiStatus: Annotated[
        list[SharedEntityStatus] | None,
        Field(description="To filter by multiple status."),
    ] = None
    facets: Annotated[
        list[ModelsFacetRequestObject] | None,
        Field(description="To filter by multiple facets."),
    ] = None


class TermRelationshipType(RootModel[Literal["Related", "Synonym", "Parent"]]):
    root: Annotated[
        Literal["Related", "Synonym", "Parent"],
        Field(description="TermRelationshipType"),
    ]


class TypePropertiesFormat(RootModel[Literal["Table", "View"]]):
    root: Annotated[Literal["Table", "View"], Field(description="The format of the SQL table.")]


class UpdateFrequencyEnum(
    RootModel[Literal["Hourly", "Daily", "Weekly", "Monthly", "Quarterly", "Yearly"]]
):
    root: Annotated[
        Literal["Hourly", "Daily", "Weekly", "Monthly", "Quarterly", "Yearly"],
        Field(description="UpdateFrequencyEnum"),
    ]


class DataAssetAdlsGen2Path(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["ADLSGen2Path"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None
    typeProperties: Annotated[
        DataAssetAdlsGen2PathTypeProperties | None,
        Field(description="Type properties of the ADLS Gen2 path asset."),
    ] = None


class DataAssetGeneral(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["General"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None


class DataAssetWithLineageAdlsGen2Path(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["ADLSGen2Path"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None
    lineage: Annotated[
        LineageObject | None,
        Field(
            description="Lineage information for the asset. See example responses for detailed structure."
        ),
    ] = None
    typeProperties: Annotated[
        DataAssetAdlsGen2PathTypeProperties | None,
        Field(description="Type properties of the ADLS Gen2 path asset."),
    ] = None


class DataAssetWithLineageGeneral(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["General"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None
    lineage: Annotated[
        LineageObject | None,
        Field(
            description="Lineage information for the asset. See example responses for detailed structure."
        ),
    ] = None


class AttributeRule(BaseModel):
    kind: Annotated[str, Field(description="The kind of attribute rule.")]
    id: Annotated[str, Field(description="The unique identifier of the attribute rule.")]
    name: Annotated[str, Field(description="The name of the attribute rule.")]
    dnfCondition: Annotated[
        list[list[Condition]],
        Field(description="The description of the attribute rule."),
    ]


class CatalogApiServiceOrderBy(BaseModel):
    field: Annotated[str | None, Field(description="The field name to order by.")] = None
    direction: Annotated[
        CatalogApiServiceOrderDirection | None,
        Field(description="The sort direction (asc or desc)."),
    ] = None


class CatalogModelKeyResult(BaseModel):
    status: Annotated[
        OverallStatusEnum | None, Field(description="The status of the key result.")
    ] = None
    systemData: Annotated[
        SystemData | None,
        Field(description="The system data associated with the key result."),
    ] = None
    id: Annotated[Uuid | None, Field(description="The unique identifier of the key result.")] = (
        None
    )
    definition: Annotated[str | None, Field(description="The definition of the key result.")] = (
        None
    )
    domainId: Annotated[Uuid | None, Field(description="The unique identifier of the domain.")] = (
        None
    )
    progress: Annotated[float | None, Field(description="The progress of the key result.")] = None
    goal: Annotated[float | None, Field(description="The goal value for the key result.")] = None
    max: Annotated[float | None, Field(description="The maximum value for the key result.")] = None


class CatalogModelRelatedCollectionParentCollection(BaseModel):
    type: Annotated[
        RelatedCollectionParentCollectionTypeEnum | None,
        Field(description="The type of the parent collection."),
    ] = None
    refName: Annotated[
        str | None, Field(description="The reference name of the parent collection.")
    ] = None


class CatalogModelSystemDataWithExpired(BaseModel):
    provisioningState: Annotated[
        DataAssetProvisioningState | None,
        Field(description="The provisioning state of the record. ex: softdeleted"),
    ] = None
    createdAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record was created."),
    ] = None
    createdBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who created the record."),
    ] = None
    lastModifiedAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record was last modified."),
    ] = None
    lastModifiedBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who last modified the record."),
    ] = None
    expiredAt: Annotated[
        AwareDatetime | None,
        Field(description="The timestamp when the record expires."),
    ] = None
    expiredBy: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the user who expired the record."),
    ] = None


class CatalogProperties(BaseModel):
    description: Annotated[str | None, Field(description="The description of the catalog.")] = None
    decisionRules: Annotated[
        list[DecisionRule] | None, Field(description="The type of the catalog.")
    ] = None
    attributeRules: Annotated[
        list[AttributeRule] | None,
        Field(description="The attribute rules of the catalog."),
    ] = None
    entity: Annotated[EntityReference, Field(description="The entity reference of the catalog.")]
    parentEntityName: Annotated[
        str | None, Field(description="The parent entity name of the catalog.")
    ] = None


class CatalogValue(BaseModel):
    name: Annotated[str, Field(description="The name of the catalog.")]
    id: Annotated[str, Field(description="The unique identifier of the catalog.")]
    version: Annotated[int, Field(description="The version of the catalog.")]
    properties: Annotated[CatalogProperties, Field(description="The properties of the catalog.")]


class CdeRelationshipWithSystemData(BaseModel):
    systemData: Annotated[
        SystemData | None, Field(description="System metadata for the relationship.")
    ] = None
    description: Annotated[str | None, Field(description="Description of the relationship.")] = (
        None
    )
    relationshipType: Annotated[str | None, Field(description="Type of the relationship.")] = None
    entityId: Annotated[Uuid, Field(description="Unique identifier of the related entity.")]


class CriticalDataElement(BaseModel):
    status: Annotated[
        CatalogModelStatus | None,
        Field(description="The current status of the critical data element."),
    ] = None
    dataType: Annotated[
        CatalogModelCriticalDataElementDataTypeEnum | None,
        Field(description="The data type of the critical data element."),
    ] = None
    id: Annotated[
        Uuid,
        Field(description="The unique identifier of the critical data element."),
    ]
    name: Annotated[str | None, Field(description="The name of the critical data element.")] = None
    systemData: Annotated[
        CatalogModelSystemDataWithExpired | None,
        Field(description="System metadata including creation and modification information."),
    ] = None
    domain: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the domain this element belongs to."),
    ] = None
    description: Annotated[
        str | None,
        Field(description="A detailed description of the critical data element."),
    ] = None
    contacts: Annotated[
        ContactsMap | None,
        Field(description="The contacts associated with this critical data element."),
    ] = None
    managedAttributes: Annotated[
        list[CatalogModelManagedAttribute] | None,
        Field(description="Managed attributes associated with this critical data element."),
    ] = None


class CriticalDataElementFacetRequest(BaseModel):
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    domainIds: Annotated[list[str] | None, Field(description="To filter by domain Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    status: Annotated[SharedEntityStatus | None, Field(description="To filter by status.")] = None
    multiStatus: Annotated[
        list[SharedEntityStatus] | None,
        Field(description="To filter by multiple status."),
    ] = None
    facets: Annotated[
        list[ModelsFacetRequestObject] | None,
        Field(description="To filter by multiple facets."),
    ] = None


class CriticalDataElementProperties(BaseModel):
    systemData: Annotated[
        SystemData | None, Field(description="System metadata for the relationship.")
    ] = None
    description: Annotated[str | None, Field(description="Description of the relationship.")] = (
        None
    )
    relationshipType: Annotated[str | None, Field(description="Type of the relationship.")] = None
    assetId: Annotated[
        Uuid | None,
        Field(description="Unique identifier of the associated asset."),
    ] = None
    entityId: Annotated[Uuid, Field(description="Name of the associated asset.")]


class CriticalDataElementQueryRequest(BaseModel):
    skip: Annotated[int | None, Field(description="Number of items to skip.")] = None
    top: Annotated[int | None, Field(description="Number of items to return.")] = None
    orderby: Annotated[
        list[CatalogApiServiceOrderBy] | None,
        Field(description="Ordering criteria for the results."),
    ] = None
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    domainIds: Annotated[list[str] | None, Field(description="To filter by domain Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    status: Annotated[SharedEntityStatus | None, Field(description="To filter by status.")] = None
    multiStatus: Annotated[
        list[SharedEntityStatus] | None,
        Field(description="To filter by multiple status."),
    ] = None
    managedAttributes: Annotated[
        list[SharedSearchManageAttributeSearchFilter] | None,
        Field(description="To filter by managed attributes."),
    ] = None


class CriticalDataElementRelationshipRequest(RootModel[dict[str, CriticalDataElementProperties]]):
    root: dict[str, CriticalDataElementProperties]


class CriticalDataElementsResponse(BaseModel):
    value: Annotated[
        list[CriticalDataElement],
        Field(description="The list of critical data elements."),
    ]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class DataAssetAzureSqlTableTypeProperties(BaseModel):
    format: Annotated[
        TypePropertiesFormat | None, Field(description="The format of the sql table.")
    ] = None
    serverEndpoint: Annotated[
        AnyUrl | None, Field(description="The server endpoint of the sql table.")
    ] = None
    databaseName: Annotated[
        str | None, Field(description="The database name of the sql table.")
    ] = None
    schemaName: Annotated[str | None, Field(description="The schema name of the sql table.")] = (
        None
    )
    tableName: Annotated[str | None, Field(description="The table name of the sql table.")] = None


class DataAssetRelationship(BaseModel):
    description: Annotated[str | None, Field(description="Description of the relationship.")] = (
        None
    )
    relationshipType: Annotated[
        DataAssetRelationshipType | None, Field(description="Type of the relationship.")
    ] = None
    entityId: Annotated[
        Uuid, Field(description="Name of the associated entity. ex:dataproduct id")
    ]


class DataColumn(BaseModel):
    id: Annotated[Uuid, Field(description="The unique identifier of the data column.")]
    source: Annotated[DataColumnSource, Field(description="The unique identifier of the asset.")]
    columnDetails: Annotated[
        DataColumnDetails | None,
        Field(
            description="Details about the column from Data Map (name, description, data type, qualified name).\nRequested by setting includeColumnDetails to true, but may be null or partially populated if enrichment fails."
        ),
    ] = None
    assetDetails: Annotated[
        DataColumnAssetDetails | None,
        Field(
            description="Details about the parent Data Governance asset (DG asset id, name, FQN).\nRequested when includeAssetDetails is true, but may be null or partial if enrichment fails."
        ),
    ] = None


class DataColumnCreateRelationshipRequest(BaseModel):
    relationshipType: Annotated[
        DataColumnRelationshipType | None,
        Field(description="The type of relationship for the data column."),
    ] = None
    entityId: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the related entity."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description for the relationship.")
    ] = None


class DataColumnCreateRelationshipResponse(BaseModel):
    relationshipType: Annotated[
        DataColumnRelationshipType | None,
        Field(description="The type of relationship for the data column."),
    ] = None
    entityId: Annotated[
        Uuid | None,
        Field(description="The unique identifier of the related entity."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description for the relationship.")
    ] = None
    systemData: Annotated[
        SystemData | None,
        Field(description="System metadata including creation and modification information."),
    ] = None


class DataColumnIngestResponse(BaseModel):
    id: Annotated[Uuid, Field(description="The unique identifier of the data column.")]
    source: Annotated[DataColumnSource, Field(description="The unique identifier of the asset.")]


class DataColumnQueryResponse(BaseModel):
    value: Annotated[
        list[DataColumn],
        Field(description="The list of data columns matching the query criteria."),
    ]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class DataColumnRelationshipResponse(BaseModel):
    value: Annotated[
        list[DataColumnRelationshipWrapper],
        Field(description="The list of data columns matching the query criteria."),
    ]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class DataProduct(BaseModel):
    status: Annotated[
        CatalogModelStatus | None, Field(description="The status of the data product.")
    ] = None
    type: Annotated[
        CatalogModelDataProductTypeEnum | None,
        Field(description="The type of the data product."),
    ] = None
    updateFrequency: Annotated[
        UpdateFrequencyEnum | None,
        Field(description="The update frequency of the data product."),
    ] = None
    managedAttributes: Annotated[
        list[CatalogModelManagedAttribute] | None,
        Field(description="The managed attributes associated with the data product."),
    ] = None
    id: Annotated[Uuid, Field(description="The unique identifier of the data product.")]
    name: Annotated[str | None, Field(description="The name of the data product.")] = None
    systemData: Annotated[
        CatalogModelSystemDataWithExpired | None,
        Field(description="The system data of the data product."),
    ] = None
    domain: Annotated[Uuid | None, Field(description="The domain of the data product.")] = None
    description: Annotated[
        str | None, Field(description="The description of the data product.")
    ] = None
    businessUse: Annotated[
        str | None, Field(description="The business use of the data product.")
    ] = None
    contacts: Annotated[
        ContactsMap | None,
        Field(description="The contacts associated with the data product."),
    ] = None
    termsOfUse: Annotated[
        list[CatalogModelExternalLink] | None,
        Field(description="The terms of use for the data product."),
    ] = None
    documentation: Annotated[
        list[CatalogModelExternalLink] | None,
        Field(description="The documentation links for the data product."),
    ] = None
    sensitivityLabel: Annotated[
        str | None, Field(description="The sensitivity label of the data product.")
    ] = None
    endorsed: Annotated[
        bool | None, Field(description="Whether the data product is endorsed.")
    ] = None
    activeSubscriberCount: Annotated[
        int | None, Field(description="The number of active subscribers.")
    ] = None
    dataQualityScore: Annotated[
        float | None, Field(description="The data quality score of the data product.")
    ] = None
    audience: Annotated[
        list[AudienceEnum] | None,
        Field(description="The target audience for the data product."),
    ] = None
    additionalProperties: Annotated[
        CatalogModelDataProductAllOfAdditionalProperties | None,
        Field(description="Additional properties of the data product."),
    ] = None


class DataProductFacetRequest(BaseModel):
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    domainIds: Annotated[list[str] | None, Field(description="To filter by domain Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    status: Annotated[SharedEntityStatus | None, Field(description="To filter by status.")] = None
    multiStatus: Annotated[
        list[SharedEntityStatus] | None,
        Field(description="To filter by multiple status."),
    ] = None
    type: Annotated[str | None, Field(description="To filter by type.")] = None
    types: Annotated[list[str] | None, Field(description="To filter by multiple types.")] = None
    facets: Annotated[
        list[ModelsFacetRequestObject] | None,
        Field(description="To filter by multiple facets."),
    ] = None


class DataProductQueryRequest(BaseModel):
    skip: Annotated[int | None, Field(description="Number of items to skip.")] = None
    top: Annotated[int | None, Field(description="Number of items to return.")] = None
    orderby: Annotated[
        list[CatalogApiServiceOrderBy] | None,
        Field(description="To order the records."),
    ] = None
    ids: Annotated[list[str] | None, Field(description="To filter by Ids.")] = None
    domainIds: Annotated[list[str] | None, Field(description="To filter by domain Ids.")] = None
    nameKeyword: Annotated[str | None, Field(description="To filter by name keyword.")] = None
    type: Annotated[str | None, Field(description="To filter by type.")] = None
    types: Annotated[list[str] | None, Field(description="To filter by multiple types.")] = None
    owners: Annotated[list[str] | None, Field(description="To filter by owners.")] = None
    status: Annotated[SharedEntityStatus | None, Field(description="To filter by status.")] = None
    multiStatus: Annotated[
        list[SharedEntityStatus] | None,
        Field(description="To filter by multiple status."),
    ] = None
    managedAttributes: Annotated[
        list[SharedSearchManageAttributeSearchFilter] | None,
        Field(description="To filter by managed attributes."),
    ] = None


class DataProductRelationship(BaseModel):
    systemData: Annotated[
        SystemData | None, Field(description="System metadata for the relationship.")
    ] = None
    description: Annotated[str | None, Field(description="Description of the relationship.")] = (
        None
    )
    relationshipType: Annotated[str | None, Field(description="Type of the relationship.")] = None
    entityId: Annotated[Uuid, Field(description="Unique identifier of the related entity.")]


class DataProductResponse(BaseModel):
    value: Annotated[list[DataProduct], Field(description="The list of data products.")]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class IngestDataColumnBatchRequest(BaseModel):
    requests: Annotated[
        list[IngestDataColumnRequest] | None,
        Field(description="The list of data column ingestion requests."),
    ] = None


class KeyResult(BaseModel):
    status: Annotated[OverallStatusEnum, Field(description="The status of the key result.")]
    systemData: Annotated[
        SystemData | None,
        Field(description="The system data associated with the key result."),
    ] = None
    id: Annotated[Uuid | None, Field(description="The unique identifier of the key result.")] = (
        None
    )
    definition: Annotated[str | None, Field(description="The definition of the key result.")] = (
        None
    )
    domainId: Annotated[Uuid, Field(description="The unique identifier of the domain.")]
    progress: Annotated[float | None, Field(description="The progress of the key result.")] = None
    goal: Annotated[float | None, Field(description="The goal value for the key result.")] = None
    max: Annotated[float | None, Field(description="The maximum value for the key result.")] = None


class ObjectiveAdditionalProperties(BaseModel):
    overallStatus: Annotated[
        OverallStatusEnum | None,
        Field(description="The overall status of the objective."),
    ] = None
    overallProgress: Annotated[
        float | None, Field(description="The overall progress of the objective.")
    ] = None
    overallGoal: Annotated[
        float | None, Field(description="The overall goal value for the objective.")
    ] = None
    overallMax: Annotated[
        float | None, Field(description="The maximum value for the objective.")
    ] = None
    keyResultsCount: Annotated[
        int | None,
        Field(description="The number of key results associated with the objective."),
    ] = None


class ObjectiveFacetRequest(BaseModel):
    ids: Annotated[list[str] | None, Field(description="Filter by objective IDs.")] = None
    domainIds: Annotated[list[str] | None, Field(description="Filter by domain IDs.")] = None
    definition: Annotated[str | None, Field(description="Filter by objective definition.")] = None
    owners: Annotated[list[str] | None, Field(description="Filter by objective owners.")] = None
    status: Annotated[
        OkrSharedEntityStatus | None, Field(description="Filter by objective status.")
    ] = None
    multiStatus: Annotated[
        list[OkrSharedEntityStatus] | None,
        Field(description="Filter by multiple objective statuses."),
    ] = None
    facets: Annotated[
        list[FacetRequestObject] | None, Field(description="Filter by facet objects.")
    ] = None


class ObjectiveQueryAdditionalProperties(BaseModel):
    status: Annotated[
        OkrSharedEntityStatus | None,
        Field(description="The overall status of the objective."),
    ] = None
    systemData: Annotated[
        OkrSystemDataWithExpired | None,
        Field(description="The system data associated with the objective."),
    ] = None
    id: Annotated[Uuid | None, Field(description="The unique identifier of the objective.")] = None
    definition: Annotated[str | None, Field(description="The definition of the objective.")] = None
    domain: Annotated[
        Uuid | None, Field(description="The domain associated with the objective.")
    ] = None
    targetDate: Annotated[
        AwareDatetime | None, Field(description="The target date for the objective.")
    ] = None
    contacts: Annotated[
        ContactsMap | None,
        Field(description="The contacts associated with the objective."),
    ] = None
    additionalProperties: Annotated[
        OverallStatusEnum | None,
        Field(description="Additional properties for objective query."),
    ] = None


class ObjectiveQueryRequest(BaseModel):
    skip: Annotated[int | None, Field(description="Number of items to skip.")] = None
    top: Annotated[int | None, Field(description="Number of items to return.")] = None
    orderby: Annotated[
        list[CatalogApiServiceOrderBy] | None,
        Field(description="Order by specifications for the query."),
    ] = None
    ids: Annotated[list[str] | None, Field(description="Filter by objective IDs.")] = None
    domainIds: Annotated[list[str] | None, Field(description="Filter by domain IDs.")] = None
    definition: Annotated[str | None, Field(description="Filter by objective definition.")] = None
    status: Annotated[
        OkrSharedEntityStatus | None, Field(description="Filter by objective status.")
    ] = None
    multiStatus: Annotated[
        list[OkrSharedEntityStatus] | None,
        Field(description="Filter by multiple objective statuses."),
    ] = None
    owners: Annotated[list[str] | None, Field(description="Filter by objective owners.")] = None
    managedAttributes: Annotated[
        list[SharedSearchManageAttributeSearchFilter] | None,
        Field(description="To filter by managed attributes."),
    ] = None


class ObjectiveWithAdditionalProperties(BaseModel):
    status: Annotated[
        OkrSharedEntityStatus | None, Field(description="The status of the objective.")
    ] = None
    systemData: Annotated[
        OkrSystemDataWithExpired | None,
        Field(description="The system data associated with the objective."),
    ] = None
    id: Annotated[Uuid, Field(description="The unique identifier of the objective.")]
    definition: Annotated[str, Field(description="The definition of the objective.")]
    domain: Annotated[
        Uuid | None, Field(description="The domain associated with the objective.")
    ] = None
    targetDate: Annotated[
        AwareDatetime | None, Field(description="The target date for the objective.")
    ] = None
    contacts: Annotated[
        ContactsMap | None,
        Field(description="The contacts associated with the objective."),
    ] = None
    additionalProperties: Annotated[
        ObjectiveAdditionalProperties | None,
        Field(description="Additional properties for the objective."),
    ] = None


class ObjectiveWithAdditionalPropertiesResponse(BaseModel):
    value: Annotated[
        list[ObjectiveWithAdditionalProperties],
        Field(description="The list of objectives with additional properties."),
    ]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class PagedCriticalDataElement(BaseModel):
    value: Annotated[
        list[CriticalDataElement],
        Field(description="The CriticalDataElement items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedDataAssetRelationship(BaseModel):
    value: Annotated[
        list[DataAssetRelationship],
        Field(description="The DataAssetRelationship items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedDataProduct(BaseModel):
    value: Annotated[list[DataProduct], Field(description="The DataProduct items on this page")]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedDataProductRelationship(BaseModel):
    value: Annotated[
        list[DataProductRelationship],
        Field(description="The DataProductRelationship items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedKeyResult(BaseModel):
    value: Annotated[list[KeyResult], Field(description="The KeyResult items on this page")]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedObjectiveWithAdditionalProperties(BaseModel):
    value: Annotated[
        list[ObjectiveWithAdditionalProperties],
        Field(description="The ObjectiveWithAdditionalProperties items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class Relationship(BaseModel):
    systemData: Annotated[
        SystemData | None, Field(description="System metadata for the relationship.")
    ] = None
    description: Annotated[str | None, Field(description="Description of the relationship.")] = (
        None
    )
    relationshipType: Annotated[str | None, Field(description="Type of the relationship.")] = None
    entityId: Annotated[Uuid, Field(description="Unique identifier of the related entity.")]


class Term(BaseModel):
    status: Annotated[CatalogModelStatus, Field(description="The status of the term.")]
    id: Annotated[Uuid, Field(description="The unique identifier of the term.")]
    name: Annotated[str, Field(description="The name of the term.")]
    systemData: Annotated[
        CatalogModelSystemDataWithExpired | None,
        Field(description="The system data of the term."),
    ] = None
    description: Annotated[str | None, Field(description="The description of the term.")] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="The contacts associated with the term.")
    ] = None
    domain: Annotated[Uuid, Field(description="The domain associated with the term.")]
    parentId: Annotated[Uuid | None, Field(description="The parent term identifier.")] = None
    acronyms: Annotated[
        list[str] | None, Field(description="The list of acronyms for the term.")
    ] = None
    resources: Annotated[
        list[CatalogModelTermResource] | None,
        Field(description="The resources associated with the term."),
    ] = None
    isLeaf: Annotated[bool | None, Field(description="Whether the term is a leaf node.")] = None
    managedAttributes: Annotated[
        list[CatalogModelManagedAttribute] | None,
        Field(description="The managed attributes associated with the term."),
    ] = None


class TermQueryRequest(BaseModel):
    skip: Annotated[int | None, Field(description="Number of items to skip.")] = None
    top: Annotated[int | None, Field(description="Number of items to return.")] = None
    orderby: Annotated[
        list[CatalogApiServiceOrderBy] | None,
        Field(description="Order by specifications for the query."),
    ] = None
    ids: Annotated[list[str] | None, Field(description="Filter by term IDs.")] = None
    domainIds: Annotated[list[str] | None, Field(description="Filter by domain IDs.")] = None
    nameKeyword: Annotated[str | None, Field(description="Filter by name keyword.")] = None
    status: Annotated[CatalogModelStatus | None, Field(description="Filter by term status.")] = (
        None
    )
    multiStatus: Annotated[
        list[CatalogModelStatus] | None,
        Field(description="Filter by multiple term statuses."),
    ] = None
    owners: Annotated[list[str] | None, Field(description="Filter by term owners.")] = None
    acronyms: Annotated[list[str] | None, Field(description="Filter by term acronyms.")] = None
    managedAttributes: Annotated[
        list[SharedSearchManageAttributeSearchFilter] | None,
        Field(description="Filter by managed attributes."),
    ] = None


class TermRelationship(BaseModel):
    systemData: Annotated[
        SystemData | None,
        Field(description="System metadata for the term relationship."),
    ] = None
    description: Annotated[
        str | None, Field(description="description for the term relationship")
    ] = None
    entityId: Annotated[Uuid, Field(description="The unique identifier of the entity.")]
    relationshipType: Annotated[
        TermRelationshipType | None,
        Field(description="The type of the term relationship."),
    ] = None


class TermResponse(BaseModel):
    value: Annotated[list[Term], Field(description="The list of terms.")]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class DataAssetAzureSqlTable(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["AzureSqlTable"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None
    typeProperties: Annotated[
        DataAssetAzureSqlTableTypeProperties | None,
        Field(description="Type properties of the Azure SQL table asset."),
    ] = None


class DataAssetWithLineageAzureSqlTable(BaseModel):
    id: Annotated[Uuid, Field(description="The data asset identifier.")]
    name: Annotated[str, Field(description="Name of the data asset.")]
    systemData: Annotated[
        DataAssetSystemData | None,
        Field(description="System data associated with the asset."),
    ] = None
    description: Annotated[
        str | None, Field(description="A description about the relationship.")
    ] = None
    source: Annotated[
        CatalogModelDataAssetSource | None, Field(description="Source of the asset.")
    ] = None
    contacts: Annotated[
        ContactsMap | None, Field(description="Contacts associated with the asset.")
    ] = None
    classifications: Annotated[
        list[str] | None, Field(description="A list of classification labels.")
    ] = None
    type: Annotated[Literal["AzureSqlTable"], Field(description="Type of the data asset.")]
    schema_: Annotated[
        list[CatalogModelDataAssetSchema] | None,
        Field(alias="schema", description="Schema of the asset."),
    ] = None
    openInUrl: Annotated[AnyUrl | None, Field(description="A redirection link.")] = None
    lineage: Annotated[
        LineageObject | None,
        Field(
            description="Lineage information for the asset. See example responses for detailed structure."
        ),
    ] = None
    typeProperties: Annotated[
        DataAssetAzureSqlTableTypeProperties | None,
        Field(description="Type properties of the Azure SQL table asset."),
    ] = None


class CatalogModelRelatedCollection(BaseModel):
    name: Annotated[str | None, Field(description="The name of the related collection.")] = None
    friendlyName: Annotated[
        str | None, Field(description="The friendly name of the related collection.")
    ] = None
    parentCollection: Annotated[
        CatalogModelRelatedCollectionParentCollection | None,
        Field(description="The parent collection of the related collection."),
    ] = None


class CatalogResponse(BaseModel):
    values: Annotated[list[CatalogValue], Field(description="The list of catalog values.")]
    skipToken: Annotated[
        str | None, Field(description="The continuation token for pagination.")
    ] = None


class PagedTerm(BaseModel):
    value: Annotated[list[Term], Field(description="The Term items on this page")]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedTermRelationship(BaseModel):
    value: Annotated[
        list[TermRelationship],
        Field(description="The TermRelationship items on this page"),
    ]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class DataAsset(RootModel[DataAssetAdlsGen2Path | DataAssetAzureSqlTable | DataAssetGeneral]):
    root: Annotated[
        DataAssetAdlsGen2Path | DataAssetAzureSqlTable | DataAssetGeneral,
        Field(discriminator="type"),
    ]


class DataAssetWithLineage(
    RootModel[
        DataAssetWithLineageAdlsGen2Path
        | DataAssetWithLineageAzureSqlTable
        | DataAssetWithLineageGeneral
    ]
):
    root: Annotated[
        DataAssetWithLineageAdlsGen2Path
        | DataAssetWithLineageAzureSqlTable
        | DataAssetWithLineageGeneral,
        Field(discriminator="type"),
    ]


class CatalogModelPlatformDomain(BaseModel):
    name: Annotated[str | None, Field(description="The name of the platform domain.")] = None
    friendlyName: Annotated[
        str | None, Field(description="The friendly name of the platform domain.")
    ] = None
    relatedCollections: Annotated[
        list[CatalogModelRelatedCollection] | None,
        Field(description="The related collections of the platform domain."),
    ] = None


class DataAssetsResponse(BaseModel):
    value: Annotated[list[DataAsset], Field(description="The list of data assets.")]
    nextLink: Annotated[str | None, Field(description="The link to the next page of results.")] = (
        None
    )


class Domain(BaseModel):
    status: Annotated[
        CatalogModelStatus | None, Field(description="The status of the domain.")
    ] = None
    type: Annotated[
        CatalogModelDomainTypeEnum | None, Field(description="The type of the domain.")
    ] = None
    id: Annotated[Uuid, Field(description="The unique identifier of the domain.")]
    name: Annotated[str | None, Field(description="The name of the domain.")] = None
    isRestricted: Annotated[
        bool | None, Field(description="Whether the domain is restricted.")
    ] = None
    systemData: Annotated[
        CatalogModelSystemDataWithExpired,
        Field(description="The system data of the domain."),
    ]
    description: Annotated[str | None, Field(description="The description of the domain.")] = None
    parentId: Annotated[Uuid, Field(description="Identifier of the domain to retrieve.")]
    thumbnail: Annotated[
        CatalogModelDomainAllOfThumbnail,
        Field(description="The thumbnail properties of the domain."),
    ]
    domains: Annotated[
        list[CatalogModelPlatformDomain],
        Field(description="The list of platform domains."),
    ]
    managedAttributes: Annotated[
        list[CatalogModelManagedAttribute],
        Field(description="The managed attributes associated with the domain."),
    ]


class PagedDataAsset(BaseModel):
    value: Annotated[list[DataAsset], Field(description="The DataAsset items on this page")]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


class PagedDomain(BaseModel):
    value: Annotated[list[Domain], Field(description="The Domain items on this page")]
    nextLink: Annotated[AnyUrl | None, Field(description="The link to the next page of items")] = (
        None
    )


DataColumnQueryFilter.model_rebuild()


# Error models from Azure.Core.Foundations
class InnerError(BaseModel):
    code: Annotated[
        str | None, Field(description="One of a server-defined set of error codes.")
    ] = None
    innererror: Annotated[InnerError | None, Field(description="Inner error.")] = None


class Error(BaseModel):
    code: Annotated[str, Field(description="One of a server-defined set of error codes.")]
    message: Annotated[str, Field(description="A human-readable representation of the error.")]
    target: Annotated[str | None, Field(description="The target of the error.")] = None
    details: Annotated[
        list[Error] | None,
        Field(
            description="An array of details about specific errors that led to this reported error."
        ),
    ] = None
    innererror: Annotated[
        InnerError | None,
        Field(
            description="An object containing more specific information than the current object about the error."
        ),
    ] = None


class ErrorResponse(BaseModel):
    error: Annotated[Error, Field(description="The error object.")]


InnerError.model_rebuild()
Error.model_rebuild()
